#Arreglos y clases
##Mátrices
Una matriz es un arreglo de n*n elementos
\[
A =
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{bmatrix}
\]

In [ ]:
A = [[1,2,3],[4,5,6],[7,8,9]]
print(A)
B=[[21,34,40],[71,17,77],[73,81,28]]
print(2*A)
#A[0,0] Esto no se puede iterar

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]


[1, 2, 3]

##Vectores y listas

In [ ]:
L= A[0]
M= B[0]
print(L+M)

[1, 2, 3, 21, 34, 40]


In [ ]:
a=L[0]
print (a)
b=M[0]
print(a+b)

1
22


In [ ]:
a==1

True

###Suma de "Vectores"

In [ ]:
len(L)==len(M)
suma=[L[0]+M[0],L[1]+M[1],L[2]+M[2]]
print(suma)

[22, 36, 43]


####Creacion de funciones globales
La función para crear funciones es `def` que se cuierra con un debug (print o return)

In [ ]:
def Hola():
  print ("Hola, me llamo Mateo")

In [ ]:
Hola()

Hola, me llamo Mateo


In [ ]:
def Saludar (s,n):
  print(f"Hola, me llamo {s} y tengo {n} años")

In [ ]:
Saludar ("Cesar",18)

Hola, me llamo Cesar y tengo 18 años


In [ ]:
def par():
  for x in range (10):
    if x%2==0:
      print(f"{x} es par")
    else:
        print(f"{x} es impar")

In [ ]:
def suma_vectorial(L,M):
  x = [L[i]+ M[i] for i in range(len(L))]
  return x

In [ ]:
L = [1,2,3]
M = [21, 34, 40]
suma_vectorial (L,M)


[22, 36, 43]

## Modulos o librerías


In [ ]:
import math
from math import *
sqrt(68)



3.141592653589793

#El módulo NumPy
La función `array`


In [ ]:
import numpy as np

l_vector = np.array(L)
m_vector = np.array(M)
l_vector+m_vector

array([22, 36, 43])

In [ ]:
C = [9,2,2,2,3,3,2,17,2]
A = [8,1,1,1,2,2,1,16,1]
C_matriz = np.array(C).reshape(3,3)
A_matriz = np.array(A).reshape(3,3)
print (C_matriz)
print (A_matriz)

[[ 9  2  2]
 [ 2  3  3]
 [ 2 17  2]]
[[ 8  1  1]
 [ 1  2  2]
 [ 1 16  1]]


In [ ]:
C_matriz @ A_matriz

array([[76, 45, 15],
       [22, 56, 11],
       [35, 68, 38]])